# Generated by Django 3.2.6 on 2021-08-06 18:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210807_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='action',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Save as a draft')], default='Draft', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0),
            preserve_default=False,
        ),
    ]
